/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.edun;

import com.mycompany.edun.database.DBConnection;
import com.mycompany.edun.quiz.ModuleQuiz;
import com.mycompany.edun.JigsawPuzzle.ModulePuzzle;
import com.mycompany.edun.crosswordpuzzle.ModuleCw;
import java.awt.Font;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nadiaag
 */
public class ChooseGame extends javax.swing.JFrame {

    public String username;

    /**
     * Creates new form choose_game
     */
    public ChooseGame(String username1) {
        initComponents();
        username = username1;
        try {
            // Add Customize Font Button
            File fontBlack = new File("src/main/resources/fonts/Nunito-Black.ttf");
            Font font_button = Font.createFont(Font.TRUETYPE_FONT, fontBlack).deriveFont(24f);
            button_Back.setFont(font_button);

            // Add Customize Font 20 Bold
            File fontButton = new File("src/main/resources/fonts/Nunito-Bold.ttf");
            Font font_20 = Font.createFont(Font.TRUETYPE_FONT, fontButton).deriveFont(20f);
            question.setFont(font_20);

            // Add Customize Font 26 Black
            Font font_24 = Font.createFont(Font.TRUETYPE_FONT, fontButton).deriveFont(26f);
            text_name.setFont(font_24);

            // Menampilkan username
            showUsername(username1);
            // Set the frame visible
            setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        icon_home = new rojerusan.RSPanelImage();
        button_Home = new rojerusan.RSMaterialButtonRectangle();
        icon_back = new rojerusan.RSPanelImage();
        button_Back = new rojerusan.RSMaterialButtonRectangle();
        txt_tts2 = new javax.swing.JLabel();
        txt_tts3 = new javax.swing.JLabel();
        tts1 = new javax.swing.JLabel();
        button_MC = new rojerusan.RSMaterialButtonRectangle();
        txt_tts1 = new javax.swing.JLabel();
        txt_tts = new javax.swing.JLabel();
        tts = new javax.swing.JLabel();
        button_TTS = new rojerusan.RSMaterialButtonRectangle();
        txt_puzzle2 = new javax.swing.JLabel();
        txt_puzzle = new javax.swing.JLabel();
        puzzle = new javax.swing.JLabel();
        button_Puzzle = new rojerusan.RSMaterialButtonRectangle();
        question = new javax.swing.JLabel();
        text_name = new javax.swing.JLabel();
        book = new javax.swing.JLabel();
        bg_choose = new javax.swing.JLabel();
        bg_pattern = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_home.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/Icon-Home.png"))); // NOI18N
        jPanel1.add(icon_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 110, 30, 30));

        button_Home.setBackground(new java.awt.Color(2, 132, 199));
        button_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Icon-Home.png"))); // NOI18N
        button_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_HomeActionPerformed(evt);
            }
        });
        jPanel1.add(button_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 90, 90, -1));

        icon_back.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/Back-Arrow.png"))); // NOI18N
        jPanel1.add(icon_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 30, 30));

        button_Back.setBackground(new java.awt.Color(244, 63, 94));
        button_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Back-Arrow.png"))); // NOI18N
        button_Back.setText("KEMBALI");
        button_Back.setAlignmentX(0.5F);
        button_Back.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        button_Back.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_Back.setIconTextGap(50);
        button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BackActionPerformed(evt);
            }
        });
        jPanel1.add(button_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 230, -1));

        txt_tts2.setFont(new java.awt.Font("Nunito", 1, 22)); // NOI18N
        txt_tts2.setForeground(new java.awt.Color(255, 255, 255));
        txt_tts2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tts2.setText("Ganda");
        jPanel1.add(txt_tts2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 650, 110, -1));

        txt_tts3.setFont(new java.awt.Font("Nunito", 1, 22)); // NOI18N
        txt_tts3.setForeground(new java.awt.Color(255, 255, 255));
        txt_tts3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tts3.setText("Pilihan");
        jPanel1.add(txt_tts3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, 110, -1));

        tts1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Multiple-Choice.png"))); // NOI18N
        jPanel1.add(tts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 100, 100));

        button_MC.setBackground(new java.awt.Color(190, 24, 93));
        button_MC.setHideActionText(true);
        button_MC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        button_MC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MCActionPerformed(evt);
            }
        });
        jPanel1.add(button_MC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 150, 220));

        txt_tts1.setFont(new java.awt.Font("Nunito", 1, 22)); // NOI18N
        txt_tts1.setForeground(new java.awt.Color(255, 255, 255));
        txt_tts1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tts1.setText("Silang");
        jPanel1.add(txt_tts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 650, 110, -1));

        txt_tts.setFont(new java.awt.Font("Nunito", 1, 22)); // NOI18N
        txt_tts.setForeground(new java.awt.Color(255, 255, 255));
        txt_tts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tts.setText("Teka Teki");
        jPanel1.add(txt_tts, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, 110, -1));

        tts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Crossword.png"))); // NOI18N
        jPanel1.add(tts, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 100, 100));

        button_TTS.setBackground(new java.awt.Color(132, 204, 22));
        button_TTS.setHideActionText(true);
        button_TTS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        button_TTS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_TTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_TTSActionPerformed(evt);
            }
        });
        jPanel1.add(button_TTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 150, 220));

        txt_puzzle2.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        txt_puzzle2.setForeground(new java.awt.Color(255, 255, 255));
        txt_puzzle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_puzzle2.setText("Puzzle");
        jPanel1.add(txt_puzzle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 650, 100, -1));

        txt_puzzle.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        txt_puzzle.setForeground(new java.awt.Color(255, 255, 255));
        txt_puzzle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_puzzle.setText("Susun");
        jPanel1.add(txt_puzzle, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, 100, -1));

        puzzle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Puzzle.png"))); // NOI18N
        jPanel1.add(puzzle, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 110, 110));

        button_Puzzle.setBackground(new java.awt.Color(29, 78, 216));
        button_Puzzle.setHideActionText(true);
        button_Puzzle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        button_Puzzle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_Puzzle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_PuzzleActionPerformed(evt);
            }
        });
        jPanel1.add(button_Puzzle, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 150, 220));

        question.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        question.setForeground(new java.awt.Color(100, 116, 139));
        question.setText("Mau main apa hari ini?");
        jPanel1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        text_name.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        text_name.setForeground(new java.awt.Color(51, 65, 85));
        text_name.setText("text_name");
        jPanel1.add(text_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Illust - Book.png"))); // NOI18N
        jPanel1.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 230, 220));

        bg_choose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BG-Choose.png"))); // NOI18N
        jPanel1.add(bg_choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, 470));

        bg_pattern.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BG.png"))); // NOI18N
        jPanel1.add(bg_pattern, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1440, 1060));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Menampilkan tulisan Nama Pengguna
    private void showUsername(String username) {
        // Membuat objek
        try {
            // 02. Query SQL
            String namaPengguna = "SELECT CONCAT('Halo, ', name, '!') AS concatUsername FROM users WHERE name = ?";

            // 03. Menghubungkan JAVA & SQL
            Connection penghubung = (Connection) DBConnection.konfigurasi_koneksiDB();

            // 04. Statement SQL dengan akses database langsung
            PreparedStatement showUsername = penghubung.prepareStatement(namaPengguna);
            showUsername.setString(1, username);

            // 05. Eksekusi perintah SQL
            ResultSet hasilSQL = showUsername.executeQuery();

            // 06. Tampilkan data
            if (hasilSQL.next()) {
                String nameDB = hasilSQL.getString("concatUsername");
                text_name.setText(nameDB);
            } else {
                text_name.setText("User not found");
            }
        } catch (Exception e) {
            // 07. Salah system
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error in showUsername: " + e.getMessage());
        }
    }

    private void button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BackActionPerformed
        // TODO add your handling code here:
        LoginUser user = new LoginUser();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_BackActionPerformed

    private void button_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_HomeActionPerformed
        // TODO add your handling code here:
        LoginMenu menu = new LoginMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_HomeActionPerformed

    private void button_PuzzleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_PuzzleActionPerformed
        // TODO add your handling code here:
        ModulePuzzle puzzle = new ModulePuzzle(username);
        puzzle.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_PuzzleActionPerformed

    private void button_MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MCActionPerformed
        // TODO add your handling code here:
        ModuleQuiz quiz = new ModuleQuiz(username);
        quiz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_MCActionPerformed

    private void button_TTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_TTSActionPerformed
        // TODO add your handling code here:
        ModuleCw tts = new ModuleCw(username);
        tts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_TTSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String username = "name";
                new ChooseGame(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_choose;
    private javax.swing.JLabel bg_pattern;
    private javax.swing.JLabel book;
    private rojerusan.RSMaterialButtonRectangle button_Back;
    private rojerusan.RSMaterialButtonRectangle button_Home;
    private rojerusan.RSMaterialButtonRectangle button_MC;
    private rojerusan.RSMaterialButtonRectangle button_Puzzle;
    private rojerusan.RSMaterialButtonRectangle button_TTS;
    private rojerusan.RSPanelImage icon_back;
    private rojerusan.RSPanelImage icon_home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel puzzle;
    private javax.swing.JLabel question;
    private javax.swing.JLabel text_name;
    private javax.swing.JLabel tts;
    private javax.swing.JLabel tts1;
    private javax.swing.JLabel txt_puzzle;
    private javax.swing.JLabel txt_puzzle2;
    private javax.swing.JLabel txt_tts;
    private javax.swing.JLabel txt_tts1;
    private javax.swing.JLabel txt_tts2;
    private javax.swing.JLabel txt_tts3;
    // End of variables declaration//GEN-END:variables
}
