/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.edun;

import com.mycompany.edun.database.DBConnection;
import java.awt.Font;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nadiaag
 */
public class LoginUser extends javax.swing.JFrame {

    /**
     * Creates new form login_user
     */
    public LoginUser() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
        try {
            // Add Customize Font Button
            File fontButton = new File("src/main/resources/fonts/Nunito-Black.ttf");
            Font font_button = Font.createFont(Font.TRUETYPE_FONT, fontButton).deriveFont(24f);
            button_Play.setFont(font_button);
            button_Back.setFont(font_button);

            // Add Customize Font 20 Black
            Font font_20 = Font.createFont(Font.TRUETYPE_FONT, fontButton).deriveFont(18f);
            text_name.setFont(font_20);

            // Add Customize Font 24 Black
            Font font_24 = Font.createFont(Font.TRUETYPE_FONT, fontButton).deriveFont(20f);
            input_name.setFont(font_24);

            // Set the frame visible
            setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        bg = new rojerusan.RSPanelImage();
        content = new javax.swing.JPanel();
        input_name = new javax.swing.JTextField();
        text_name = new javax.swing.JLabel();
        icon_play = new rojerusan.RSPanelImage();
        button_Play = new rojerusan.RSMaterialButtonRectangle();
        bg_name = new rojerusan.RSPanelImage();
        character_kids = new rojerusan.RSPanelImage();
        cta = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        icon_back = new rojerusan.RSPanelImage();
        button_Back = new rojerusan.RSMaterialButtonRectangle();
        jPanel5 = new javax.swing.JPanel();
        icon_home = new rojerusan.RSPanelImage();
        button_Home = new rojerusan.RSMaterialButtonRectangle();
        jMenuBar1 = new javax.swing.JMenuBar();
        eduN = new javax.swing.JMenu();
        credits = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();
        quit = new javax.swing.JMenuItem();
        tools = new javax.swing.JMenu();
        loginAdmin = new javax.swing.JMenuItem();
        logoutAdmin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login User");

        jDesktopPane1.setEnabled(false);

        jPanel1.setOpaque(false);

        bg.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/BG.png"))); // NOI18N

        content.setOpaque(false);
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input_name.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        input_name.setForeground(new java.awt.Color(15, 23, 42));
        input_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        input_name.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(148, 163, 184)));
        input_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_name.setMargin(new java.awt.Insets(100, 6, 2, 6));
        input_name.setName(""); // NOI18N
        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });
        content.add(input_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 430, 60));

        text_name.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        text_name.setForeground(new java.awt.Color(51, 65, 85));
        text_name.setText("SIAPA NAMA KAMU?");
        content.add(text_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        icon_play.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/Icon-Play.png"))); // NOI18N
        content.add(icon_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 30, 30));

        button_Play.setBackground(new java.awt.Color(124, 58, 237));
        button_Play.setText("MULAI PERMAINAN");
        button_Play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Play.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        button_Play.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_PlayActionPerformed(evt);
            }
        });
        content.add(button_Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 410, -1));

        bg_name.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/BG-Name.png"))); // NOI18N
        content.add(bg_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 460, 340));

        character_kids.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/Cartoon.png"))); // NOI18N
        content.add(character_kids, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 300));

        cta.setOpaque(false);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_back.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/Back-Arrow.png"))); // NOI18N
        jPanel3.add(icon_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        button_Back.setBackground(new java.awt.Color(244, 63, 94));
        button_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Back-Arrow.png"))); // NOI18N
        button_Back.setText("KEMBALI");
        button_Back.setAlignmentX(0.5F);
        button_Back.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        button_Back.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_Back.setIconTextGap(50);
        button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BackActionPerformed(evt);
            }
        });
        jPanel3.add(button_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_home.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/Icon-Home.png"))); // NOI18N
        jPanel5.add(icon_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 30));

        button_Home.setBackground(new java.awt.Color(2, 132, 199));
        button_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Icon-Home.png"))); // NOI18N
        button_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_HomeActionPerformed(evt);
            }
        });
        jPanel5.add(button_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        javax.swing.GroupLayout ctaLayout = new javax.swing.GroupLayout(cta);
        cta.setLayout(ctaLayout);
        ctaLayout.setHorizontalGroup(
            ctaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ctaLayout.setVerticalGroup(
            ctaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ctaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap(480, Short.MAX_VALUE)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(480, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(cta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(242, 242, 242))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(cta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        eduN.setText("eduN");

        credits.setText("Credits");
        credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsActionPerformed(evt);
            }
        });
        eduN.add(credits);

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        eduN.add(about);

        quit.setText("Keluar eduN");
        eduN.add(quit);

        jMenuBar1.add(eduN);

        tools.setText("Alat");
        tools.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginAdmin.setText("Masuk Admin");
        loginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAdminActionPerformed(evt);
            }
        });
        tools.add(loginAdmin);

        logoutAdmin.setText("Keluar Admin");
        logoutAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logoutAdmin.setEnabled(false);
        logoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutAdminActionPerformed(evt);
            }
        });
        tools.add(logoutAdmin);

        jMenuBar1.add(tools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(1440, 1052));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_input_nameActionPerformed

    private void button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BackActionPerformed
        // TODO add your handling code here:
        LoginMenu menu = new LoginMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_BackActionPerformed

    private void button_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_PlayActionPerformed
        // TODO add your handling code here:

        // 01. Tangkap variable inputan dari GUI
        String username = input_name.getText();

        try {
            // 02. Query SQL
            String addNewUser = "INSERT INTO users (name) VALUES (?)";

            // 03. Menghubungkan JAVA & SQL
            Connection penghubung = (Connection) DBConnection.konfigurasi_koneksiDB();

            // 04. Statement SQL dengan akses database langsung (memodifikasi data)
            PreparedStatement newUser = penghubung.prepareStatement(addNewUser);
            newUser.setString(1, username);

            // 05. Eksekusi perintah SQL
            int rowsInserted = newUser.executeUpdate();

            if (rowsInserted > 0) {
                // 06. Validasi SQL dan lanjut ke halaman berikutnya
                ChooseGame game = new ChooseGame(username);
                game.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }

        } catch (Exception e) {
            // 07. Salah system
        }
    }//GEN-LAST:event_button_PlayActionPerformed

    private void creditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsActionPerformed
        // TODO add your handling code here:
        Credits c = new Credits();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_creditsActionPerformed

    private void loginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAdminActionPerformed
        // TODO add your handling code here:
        LoginAdmin admin = new LoginAdmin();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginAdminActionPerformed

    private void logoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutAdminActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        About a = new About();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_aboutActionPerformed

    private void button_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_HomeActionPerformed
        // TODO add your handling code here:
        LoginMenu menu = new LoginMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private rojerusan.RSPanelImage bg;
    private rojerusan.RSPanelImage bg_name;
    private rojerusan.RSMaterialButtonRectangle button_Back;
    private rojerusan.RSMaterialButtonRectangle button_Home;
    private rojerusan.RSMaterialButtonRectangle button_Play;
    private rojerusan.RSPanelImage character_kids;
    private javax.swing.JPanel content;
    private javax.swing.JMenuItem credits;
    private javax.swing.JPanel cta;
    private javax.swing.JMenu eduN;
    private rojerusan.RSPanelImage icon_back;
    private rojerusan.RSPanelImage icon_home;
    private rojerusan.RSPanelImage icon_play;
    private javax.swing.JTextField input_name;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenuItem loginAdmin;
    private javax.swing.JMenuItem logoutAdmin;
    private javax.swing.JMenuItem quit;
    private javax.swing.JLabel text_name;
    private javax.swing.JMenu tools;
    // End of variables declaration//GEN-END:variables

}
