/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.edun;

import java.awt.Font;
import java.io.File;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lusi Alifatul Laila
 */
public class login_menu extends javax.swing.JFrame {

    /**
     * Creates new form login_menu
     */
    public login_menu() {
        initComponents();
        
        try {
            // Add Customize Font Button
           File fontButton = new File("src/main/resources/fonts/Nunito-Black.ttf");
           Font font_button = Font.createFont(Font.TRUETYPE_FONT, fontButton).deriveFont(24f);
           button_play.setFont(font_button);
           button_exit.setFont(font_button);
        } catch (Exception e) {
           e.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_exit = new rojerusan.RSMaterialButtonRectangle();
        button_play = new rojerusan.RSMaterialButtonRectangle();
        title = new javax.swing.JLabel();
        bg_pattern = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_exit.setBackground(new java.awt.Color(255, 51, 102));
        button_exit.setText("KELUAR");
        button_exit.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exitActionPerformed(evt);
            }
        });
        getContentPane().add(button_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 171, 60));

        button_play.setBackground(new java.awt.Color(124, 58, 237));
        button_play.setText("MULAI PERMAINAN");
        button_play.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        button_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_playActionPerformed(evt);
            }
        });
        getContentPane().add(button_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 555, 393, -1));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Title.png"))); // NOI18N
        title.setMaximumSize(new java.awt.Dimension(681, 325));
        title.setMinimumSize(new java.awt.Dimension(681, 325));
        title.setPreferredSize(new java.awt.Dimension(681, 325));
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 187, 681, 325));

        bg_pattern.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BG.png"))); // NOI18N
        getContentPane().add(bg_pattern, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1020));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("EXIT");
        System.exit(0);
//        if (JOptionPane.showConfirmDialog(frame, "")==JOptionPane.YES_NO_OPTION) {
//            System.exit(0);
//        }
    }//GEN-LAST:event_button_exitActionPerformed

    private void button_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_playActionPerformed
        // TODO add your handling code here:
        login_user user = new login_user();
        jDesktopPane1.add(user);
        user.setVisible(true);
        user.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_button_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_pattern;
    private rojerusan.RSMaterialButtonRectangle button_exit;
    private rojerusan.RSMaterialButtonRectangle button_play;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
