/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.edun;

import java.awt.Font;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lusi Alifatul Laila
 */
public class LoginMenu extends javax.swing.JFrame {

    /**
     * Creates new form login_menu
     */
    public LoginMenu() {
        initComponents();
        
        try {
            // Add Customize Font Button
           File fontButton = new File("src/main/resources/fonts/Nunito-Black.ttf");
           Font font_button = Font.createFont(Font.TRUETYPE_FONT, fontButton).deriveFont(24f);
           button_Play.setFont(font_button);
           button_exit.setFont(font_button);
        } catch (Exception e) {
           e.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_exit = new rojerusan.RSMaterialButtonRectangle();
        icon_play = new rojerusan.RSPanelImage();
        button_Play = new rojerusan.RSMaterialButtonRectangle();
        title = new javax.swing.JLabel();
        bg_pattern = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_exit.setBackground(new java.awt.Color(255, 51, 102));
        button_exit.setText("KELUAR");
        button_exit.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exitActionPerformed(evt);
            }
        });
        getContentPane().add(button_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 171, 60));

        icon_play.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/Icon-Play.png"))); // NOI18N
        getContentPane().add(icon_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 30, 30));

        button_Play.setBackground(new java.awt.Color(124, 58, 237));
        button_Play.setText("MULAI PERMAINAN");
        button_Play.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        button_Play.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_PlayActionPerformed(evt);
            }
        });
        getContentPane().add(button_Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 410, -1));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Title.png"))); // NOI18N
        title.setMaximumSize(new java.awt.Dimension(681, 325));
        title.setMinimumSize(new java.awt.Dimension(681, 325));
        title.setPreferredSize(new java.awt.Dimension(681, 325));
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 187, 700, 325));

        bg_pattern.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BG.png"))); // NOI18N
        getContentPane().add(bg_pattern, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("EXIT");
        System.exit(0);
        if (JOptionPane.showConfirmDialog(frame, "")==JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_button_exitActionPerformed

    private void button_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_PlayActionPerformed
        // TODO add your handling code here:
        LoginUser user = new LoginUser();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_PlayActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_pattern;
    private rojerusan.RSMaterialButtonRectangle button_Play;
    private rojerusan.RSMaterialButtonRectangle button_exit;
    private rojerusan.RSPanelImage icon_play;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
