/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.edun;

import com.mycompany.edun.database.DBConnection;
import java.awt.Font;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lusi Alifatul Laila
 */
public class SucceedGameFrame extends javax.swing.JFrame {

    int newId;
    String newName;
    int newMarks;
    String newGameType;
    boolean isLoop = false;

    /**
     * Creates new form sukses
     */
    public SucceedGameFrame() {
        initComponents();
        try {
            File fontBlack = new File("src/main/resources/fonts/Nunito-Black.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, fontBlack).deriveFont(24f);
            button_try.setFont(font);
            button_next.setFont(font);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public SucceedGameFrame(String inputName, int inputMarks, String inputGameType, int inputId) {
        initComponents();
        newId = inputId;
        newName = inputName;
        newMarks = inputMarks;
        newGameType = inputGameType.toUpperCase();
        if (newMarks <= 20) {
            icon_star1.setVisible(false);
            icon_star2.setVisible(false);
            icon_star3.setVisible(false);
        } else if (newMarks <= 50) {
            icon_star1.setVisible(true);
            icon_star2.setVisible(false);
            icon_star3.setVisible(false);
        } else if (newMarks <= 80) {
            icon_star1.setVisible(true);
            icon_star2.setVisible(true);
            icon_star3.setVisible(false);
        } else {
            icon_star1.setVisible(true);
            icon_star2.setVisible(true);
            icon_star3.setVisible(true);
        }
        skor_pengguna.setText(newName);
        text_PTS.setText(newMarks + " PTS");
        isLoop = true;
    }

    public SucceedGameFrame(String inputName, int inputMarks, String inputGameType) {
        initComponents();
        newName = inputName;
        newMarks = inputMarks;
        newGameType = inputGameType.toUpperCase();
        if (newMarks <= 20) {
            icon_star1.setVisible(false);
            icon_star2.setVisible(false);
            icon_star3.setVisible(false);
        } else if (newMarks <= 50) {
            icon_star1.setVisible(true);
            icon_star2.setVisible(false);
            icon_star3.setVisible(false);
        } else if (newMarks <= 80) {
            icon_star1.setVisible(true);
            icon_star2.setVisible(true);
            icon_star3.setVisible(false);
        } else {
            icon_star1.setVisible(true);
            icon_star2.setVisible(true);
            icon_star3.setVisible(true);
        }
        skor_pengguna.setText(newName);
        text_PTS.setText(newMarks + " PTS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        rSPanelImage2 = new rojerusan.RSPanelImage();
        jPanel1 = new javax.swing.JPanel();
        text_hebat = new javax.swing.JLabel();
        icon_piala = new javax.swing.JLabel();
        icon_star1 = new javax.swing.JLabel();
        icon_star2 = new javax.swing.JLabel();
        icon_star3 = new javax.swing.JLabel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        button_home = new rojerusan.RSMaterialButtonRectangle();
        text_skorKamu = new javax.swing.JLabel();
        skor_pengguna = new javax.swing.JLabel();
        text_PTS = new javax.swing.JLabel();
        icon_restart = new javax.swing.JLabel();
        button_try = new rojerusan.RSMaterialButtonRectangle();
        button_next = new rojerusan.RSMaterialButtonRectangle();
        mask_group = new javax.swing.JLabel();
        background_front = new javax.swing.JLabel();
        background_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));

        jPanel2.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel2.setPreferredSize(new java.awt.Dimension(1440, 1024));

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/BG2.png"))); // NOI18N
        rSPanelImage2.setMinimumSize(new java.awt.Dimension(1440, 1024));
        rSPanelImage2.setPreferredSize(new java.awt.Dimension(1440, 1024));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_hebat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Text Hebat.png"))); // NOI18N
        jPanel1.add(text_hebat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        icon_piala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon piala.png"))); // NOI18N
        jPanel1.add(icon_piala, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        icon_star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star1.png"))); // NOI18N
        jPanel1.add(icon_star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        icon_star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star2.png"))); // NOI18N
        jPanel1.add(icon_star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        icon_star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star1.png"))); // NOI18N
        jPanel1.add(icon_star3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/assets/Icon-Home.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 30, 30));

        button_home.setBackground(new java.awt.Color(2, 132, 199));
        button_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homeActionPerformed(evt);
            }
        });
        jPanel1.add(button_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, -1));

        text_skorKamu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        text_skorKamu.setText("SKOR KAMU");
        jPanel1.add(text_skorKamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        skor_pengguna.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        skor_pengguna.setText("[SKOR PENGGUNA]");
        jPanel1.add(skor_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        text_PTS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text_PTS.setText("PTS");
        jPanel1.add(text_PTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        icon_restart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon restart.png"))); // NOI18N
        jPanel1.add(icon_restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        button_try.setBackground(new java.awt.Color(255, 204, 51));
        button_try.setText("MAIN LAGI");
        button_try.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        button_try.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tryActionPerformed(evt);
            }
        });
        jPanel1.add(button_try, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 249, -1));

        button_next.setBackground(new java.awt.Color(0, 153, 102));
        button_next.setText("SELANJUTNYA");
        button_next.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        button_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nextActionPerformed(evt);
            }
        });
        jPanel1.add(button_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 272, -1));

        mask_group.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Mask group.png"))); // NOI18N
        jPanel1.add(mask_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        background_front.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Background Front.png"))); // NOI18N
        jPanel1.add(background_front, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        background_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Background Back.png"))); // NOI18N
        jPanel1.add(background_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage2Layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(rSPanelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 1446, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1446, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homeActionPerformed
        // TODO add your handling code here:
        LoginMenu menu = new LoginMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_homeActionPerformed

    private void button_tryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tryActionPerformed
        // TODO add your handling code here:
        ChooseGame chooseMenu = new ChooseGame(newName);
        chooseMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_tryActionPerformed

    private void button_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nextActionPerformed
        // TODO add your handling code here:
        if (!isLoop) {
            Leaderboard board = new Leaderboard(newName, newMarks, newGameType);
            board.setVisible(true);
            this.dispose();
        } else {
            Leaderboard board = null;
            try {
                board = new Leaderboard(newName, newMarks, newGameType, newId);
            } catch (SQLException ex) {
                Logger.getLogger(SucceedGameFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            board.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_button_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SucceedGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SucceedGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SucceedGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SucceedGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SucceedGameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_back;
    private javax.swing.JLabel background_front;
    private rojerusan.RSMaterialButtonRectangle button_home;
    private rojerusan.RSMaterialButtonRectangle button_next;
    private rojerusan.RSMaterialButtonRectangle button_try;
    private javax.swing.JLabel icon_piala;
    private javax.swing.JLabel icon_restart;
    private javax.swing.JLabel icon_star1;
    private javax.swing.JLabel icon_star2;
    private javax.swing.JLabel icon_star3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mask_group;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojerusan.RSPanelImage rSPanelImage2;
    private javax.swing.JLabel skor_pengguna;
    private javax.swing.JLabel text_PTS;
    private javax.swing.JLabel text_hebat;
    private javax.swing.JLabel text_skorKamu;
    // End of variables declaration//GEN-END:variables
}
